server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  include /etc/nginx/mime.types;
  location / { try_files $uri $uri/ /index.html; }
  location /health { access_log off; return 200 'ok'; add_header Content-Type text/plain; }
}
